In [2]:
import os
os.sys.path.append(os.path.dirname(os.path.abspath('.')))
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [4]:
# Import local modules
from src.eigenvectors import eigen

In [41]:
# Create random real symmetric matrix
np.random.seed(43)
Q = np.random.randn(6, 6)
A = 0.5*(Q.transpose() + Q)

#Compute eigenvector corresponding to minimal eigenvalue:
tf.reset_default_graph()
computed_min_eigenvector = eigen(A, 5, [5, 5], tolerance=0.000001, max_value=False).ravel()
print(computed_min_eigenvector)

Iteration 0
[-0.48325111 -0.09880817 -0.37293659 -0.56234451  0.52036131 -0.17497534]


In [42]:
#Compute eigenvector corresponding to maximal eigenvalue:
tf.reset_default_graph()
computed_max_eigenvector = eigen(A, 5, [5, 5], tolerance=0.000001).ravel()
print(computed_max_eigenvector)

Iteration 0
[-0.29924905  0.70447592  0.13396706 -0.056682    0.09878272  0.61906836]


In [43]:
# Compute solutions using numpy
eigenpairs = np.linalg.eig(A)
min_index = np.argmin(eigenpairs[0])
max_index = np.argmax(eigenpairs[0])

numpy_min_eigenvector = eigenpairs[1][:, min_index]
numpy_max_eigenvector = eigenpairs[1][:, max_index]
print(numpy_min_eigenvector)
print(numpy_max_eigenvector)

[-0.48325113 -0.09880754 -0.37293672 -0.56234454  0.52036144 -0.17497488]
[ 0.29925207 -0.7044717  -0.13396935  0.05667731 -0.0987871  -0.61907093]


In [44]:
# If eigenvectors point in opposite direction, multiply by -1:
if (computed_min_eigenvector[0] < 0 and numpy_min_eigenvector[0] > 0):
    computed_min_eigenvector *= -1
if (computed_min_eigenvector[0] > 0 and numpy_min_eigenvector[0] < 0):
    computed_min_eigenvector *= -1
if (computed_max_eigenvector[0] < 0 and numpy_max_eigenvector[0] > 0):
    computed_max_eigenvector *= -1
if (computed_max_eigenvector[0] > 0 and numpy_max_eigenvector[0] < 0):
    computed_max_eigenvector *= -1    

In [49]:
# Compute mse scores:
print('MSE for eigenvector corresponding to smallest eigenvalue:', mean_squared_error(numpy_min_eigenvector, computed_min_eigenvector))
print('MSE for eigenvector corresponding to largest eigenvalue:', mean_squared_error(numpy_max_eigenvector, computed_max_eigenvector))


MSE for eigenvector corresponding to smallest eigenvalue: 1.0570422148892076e-13
MSE for eigenvector corresponding to largest eigenvalue: 1.3322730244124061e-11
